# Generated by Django 2.1.7 on 2019-04-25 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_level', models.CharField(choices=[('G', 'Vàng'), ('S', 'Bạc'), ('D', 'Mặc định')], default='D', max_length=1)),
                ('account_type', models.CharField(choices=[('A', 'Trung Tâm'), ('S', 'Học sinh'), ('T', 'Gia sư')], default='S', max_length=1)),
                ('is_agreed', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
