# Generated by Django 2.1.7 on 2019-05-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('A', 'Trung tâm'), ('S', 'Học sinh'), ('T', 'Gia sư')], default='S', max_length=1),
        ),
    ]
