# Generated by Django 2.1.5 on 2019-03-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('account_level', models.CharField(choices=[('G', 'Gold'), ('S', 'Silver'), ('C', 'Copper')], max_length=1)),
                ('account_type', models.CharField(choices=[('B', 'Business'), ('S', 'Student'), ('T', 'Teacher')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='InformationPersonal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to='')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('job', models.CharField(max_length=255)),
            ],
        ),
    ]
