# Generated by Django 2.1.5 on 2019-03-21 15:35

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyProcess',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('qualification', models.CharField(max_length=255)),
                ('trainingcenter', models.CharField(max_length=255)),
                ('medium_score', models.IntegerField()),
                ('Educationlevel', models.CharField(choices=[('C', 'College'), ('U', 'University'), ('M', 'Master'), ('P', 'Doctor'), ('A', 'Another')], default='College', max_length=2)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('classification', models.CharField(max_length=100)),
                ('certificate', models.ImageField(upload_to='')),
                ('academic_transcript', models.ImageField(upload_to='')),
                ('trainingtime', models.DateTimeField(max_length=200)),
            ],
        ),
    ]
