# Generated by Django 2.1.5 on 2019-03-21 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190321_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('detail', models.TextField()),
                ('id_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=255)),
                ('register_day', models.DateTimeField()),
                ('name_course', models.CharField(max_length=255)),
                ('address_class', models.CharField(max_length=255)),
                ('start_day', models.DateTimeField()),
                ('tuition', models.DecimalField(decimal_places=4, max_digits=8)),
                ('estimated_size', models.IntegerField()),
                ('attended_size', models.IntegerField()),
                ('condition_class', models.CharField(choices=[('O', 'Open'), ('C', 'Close'), ('R', 'Running')], default='Select', max_length=1)),
                ('id_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Account')),
            ],
        ),
        migrations.CreateModel(
            name='StudentExample',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('Block', models.CharField(max_length=50)),
                ('Achivement', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='address',
            new_name='address_user',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=True, max_length=70, unique='@gmailcom'),
        ),
        migrations.AlterField(
            model_name='studyprocess',
            name='Education_level',
            field=models.CharField(choices=[('C', 'College'), ('U', 'University'), ('M', 'Master'), ('P', 'Doctor'), ('A', 'Another')], default='College', max_length=1),
        ),
    ]
