# Generated by Django 2.1.7 on 2019-04-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190321_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='id_comment',
        ),
        migrations.RemoveField(
            model_name='class',
            name='id_manager',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='InformationPersonal',
        ),
        migrations.DeleteModel(
            name='Introduction',
        ),
        migrations.DeleteModel(
            name='StudentExample',
        ),
        migrations.DeleteModel(
            name='StudyProcess',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
