# Generated by Django 2.1.7 on 2019-04-25 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('polls', '0005_auto_20190425_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='PERSONALINFORMATION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to='')),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('job', models.CharField(max_length=255)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
    ]
