# Generated by Django 2.1.7 on 2019-04-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('polls', '0006_personalinformation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PERSONALINFORMATION',
            new_name='UserInfo',
        ),
    ]
