# Generated by Django 2.1.7 on 2019-05-05 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190428_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='fullname',
        ),
    ]
