# Generated by Django 2.1.7 on 2019-05-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20190505_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='gender',
        ),
    ]
