# Generated by Django 2.1.7 on 2019-05-13 12:19

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190509_1111'),
        ('polls', '0014_schedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=255)),
                ('training_center', models.CharField(max_length=255)),
                ('gpa', models.DecimalField(blank=True, decimal_places=1, max_digits=11)),
                ('education_level', models.CharField(choices=[('C', 'Cao Đẳng'), ('U', 'Đại Học'), ('M', 'Thạc Sỹ'), ('P', 'Tiến Sỹ'), ('A', 'Khác')], default='A', max_length=1)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('classification', models.CharField(choices=[('Xuất sắc', 'Xuất sắc'), ('Giỏi', 'Giỏi'), ('Khá', 'Khá'), ('Trung bình', 'Trung bình')], default='Khá', max_length=10)),
                ('certificate', models.ImageField(upload_to='')),
                ('training_time_start', models.DateField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
    ]
