# Generated by Django 2.1.7 on 2019-05-13 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_studyprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprocess',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=11, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
    ]
