# Generated by Django 2.1.7 on 2019-05-13 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20190513_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprocess',
            name='gpa',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
    ]
