# Generated by Django 2.1.7 on 2019-05-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20190513_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprocess',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=11),
        ),
    ]
