# Generated by Django 2.1.7 on 2019-05-13 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190509_1111'),
        ('polls', '0018_auto_20190513_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('register_day', models.DateTimeField()),
                ('address', models.CharField(max_length=255)),
                ('start_day', models.DateTimeField()),
                ('end_day', models.DateTimeField()),
                ('tuition_fee', models.DecimalField(decimal_places=4, max_digits=8)),
                ('maximum_student', models.IntegerField()),
                ('registration_number', models.IntegerField()),
                ('class_status', models.CharField(choices=[('O', 'Bắt đầu chiêu sinh'), ('C', 'Ngưng chiêu sinh'), ('R', 'Đang dạy'), ('E', 'Kết thúc')], default='C', max_length=1)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Classes')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('avatar', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
    ]
