# Generated by Django 2.1.7 on 2019-05-13 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190509_1111'),
        ('polls', '0019_classes_courses_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypicalStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('achievement', models.CharField(max_length=255)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
    ]
