# Generated by Django 2.1.7 on 2019-05-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_typicalstudents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typicalstudents',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='typicalstudents',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='typicalstudents',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='typicalstudents',
            name='subject',
        ),
        migrations.AddField(
            model_name='typicalstudents',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
