# Generated by Django 2.1.7 on 2019-05-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20190514_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='classes',
            name='thumbnail',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
